version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    image: postgres

  mongodb:
    ports:
      - "27017:27017"
    image: mongo
  redis:
    ports:
      - "6379:6379"
    image: redis:alpine
